### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by billyvg** [neovim/node-host#15]
Any plans to promisify the neovim client API?

Would you rather see it done in this package, `node-client`, or a forked package?

Related issues:

https://github.com/neovim/node-client/issues/11
https://github.com/neovim/node-client/pull/7

**Comment by justinmk** [comment]
@rhysd has a fork that adds a promise API.

**Comment by justinmk** [comment]
See https://github.com/rhysd/promised-neovim-client

**Comment by billyvg** [comment]
Yeah I'm just trying to gauge interest on how to handle it - ideally I would like to avoid maintaining a separate fork, but if there are no plans to add promises, then that's what I'll do. Also if there are plans, I can try to add that in.

**Comment by justinmk** [comment]
Doesn't https://github.com/rhysd/promised-neovim-client fit your needs? Or why would you need to maintain another fork?

There are not plans to add promise API to this repo. If it's a really important feature, given that https://github.com/rhysd/promised-neovim-client is somewhat battle-tested and there seems to be rising interest, perhaps we should discuss merging https://github.com/rhysd/promised-neovim-client back in. @rhysd @tarruda @nhynes what do you think?

**Comment by billyvg** [comment]
Wouldn't I need a fork of `node-host` that uses `promised-neovim-client` instead of `neovim-client`?

**Comment by tarruda** [comment]
I stand by my [comment](https://github.com/neovim/node-client/pull/7#issuecomment-150777717) when @rhysd first suggested a promise-based API for the client: I don't have anything against, but it should be optional because callback APIs is what node.js standard library uses and some node programmers may not like promises.

This is not a problem for promise API consumers(eg: [co](https://github.com/tj/co)) since it is very easy to wrap any callback API into promises (libraries like bluebird support this out-of-box). Take [mz](https://github.com/normalize/mz) for example, it wraps the entire node.js standard library into promises and is no more than a couple hundred lines of code.

When I first suggested a separate package for promises, I was hoping @rhysd would build [promised-neovim-client](https://github.com/rhysd/promised-neovim-client) on top of the existing callback-based client, but now I see that it was simply forked, which is a more cumbersome path since any client changes will have to be replicated in both packages.

**Comment by rhysd** [comment]
@tarruda @justinmk @billyvg 

I see.  Then I think I can create a pull request again!  Making callback optional.  It will not break current APIs.

**Comment by rhysd** [comment]
I didn't like to use a wrapper such as bluebird because it makes callstack deeper and debugging harder.  And I could not predict its overhead.  Actually RPC is a bottle neck of my app according to DevTools.

**Comment by rhysd** [comment]
@tarruda @justinmk @billyvg 

I noticed that existence of callback is used to determine to request or notify the API.

https://github.com/neovim/node-client/blob/master/index.js#L54

If we decided to return Promise value when callback not specified,  we always need to use request because API function can't know the returned Promise value is actually used or not.  What do you think?

**Comment by tarruda** [comment]
> If we decided to return Promise value when callback not specified, we always need to use request because API function can't know the returned Promise value is actually used or not. What do you think?

If a caller is using the promise-wrapped API, assume only requests will be sent, and you will always have to pass a callback in this case(since the callback is provided by your code, which is wrapping the callback API into promises)

**Comment by rhysd** [comment]
@tarruda 

So, do you mean that there should be 2 APIs for each remote API such as `nvim.command(cmd: string, cb?: Function): void` and `nvim.command2(cmd: string): Promise<void>`? Although we need to consider the name of wrapped APIs.

**Comment by tarruda** [comment]
> So, do you mean that there should be 2 APIs for each remote API such as nvim.command(cmd: string, cb?: Function): void and nvim.command2(cmd: string): Promise<void>?

Yes

> Although we need to consider the name of wrapped APIs.

The name can be the same, all we need is to return an object with APIs wrapped. Here's how I imagine the README example using [co](https://github.com/tj/co) would look like:

``` js

var cp = require('child_process');
var attach = require('neovim-client/promisified');
var co = require('co');

var nvim_proc = cp.spawn('nvim', ['-u', 'NONE', '-N', '--embed'], {});
co(function*() {
  var nvim = yield attach(nvim_proc.stdin, nvim_proc.stdout);

  nvim.on('request', (method, args, resp) => co(function*() {
    // handle msgpack-rpc request
  }).then((result) => resp.send(result)).catch((err) => resp.send(err.message, true)));

  nvim.on('notification', (method, args) => co(function*() {
    // handle msgpack-rpc notification
  }));

  var res = yield nvim.command('vsp');
  var windows = yield nvim.getWindows();
  console.log(windows.length);  // 2
  console.log(windows[0] instanceof nvim.Window); // true
  console.log(windows[1] instanceof nvim.Window); // true
  yield nvim.setCurrentWindow(windows[1]);
  var win = yield nvim.getCurrentWindow();
  console.log(win.equals(windows[1]))  // true
  yield nvim.quit();
  console.log("Nvim exited!");
}).catch((err) => console.log(err));
```

The implementation of the promisified version of `attach` should be quite simple:
- Call `attach`(the non-promisified version) and return a promise for it
- On the `attach` promise resolution, iterate through each class/method, wrap into a promise-aware version and return the promisified API object. The iteration logic can be copied/pasted from the typescript interface generator.
