### ISSUE TITLE
Drop global install requirement

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/node-host#29]
The previous version which used a local version of neovim was a feature as it didn't require sudo to run. The locality is a feature of the node ecosystem.

Is there a strong benefit to making the install process be global?

**Comment by billyvg** [comment]
Installing npm packages globally should not require sudo, your global`node_modules` dir may have stricter permissions. If this is the case, as long as `neovim-node-host` is in your PATH, it will run fine.

The benefit to making it global is to simplify the install instructions to get up and running (ideally).

**Comment by SevereOverfl0w** [comment]
On all linux machines I've used, this has been the case.

I felt the local install was simpler, no?

**Comment by billyvg** [comment]
In our case we are using npm as more of a system package manager because nvim depends on the `neovim-node-host` executable. There are a few ways to solve this, but I think `-g` is the easiest to describe in docs, of course I'm willing to accept PRs for additional instructions in docs.

*Edit* just woke up, it may work if you install it locally (it'd install locally to the nvim bin I'd assume), but I haven't tested it.

**Comment by billyvg** [comment]
Also keep in mind that previously, `node-host` was the vim scripts as well the node.js host, which meant that you could run npm install locally because everything was local to each other. The reason for splitting the vim scripts from node.js scripts is because we want to move this repo into the neovim client itself and it will function the same way as this current plugin.

**Comment by SevereOverfl0w** [comment]
I'm thinking of local to the plugin node host. The way I perceive it, is as
acting as a host in it's own right. Where the install instructions involve
`npm install` only, which gives me isolation.

Then something like `npm run neovim-host ` can be used to start the binary.

I really like being able to nuke the plugin by killing it's local folder
entirely.

**Comment by SevereOverfl0w** [comment]
A simple solution would be to have this plugin have a tiny package.json
which depends on neovim, and has a npm script for running the binary.

You get locality and the binary. You get the benefits of avoiding sudo, and
as the author of this plugin you can pin the version of the npm package
that you work with. This also makes it easier for users to move forward and
backward in case of bugs.

**Comment by justinmk** [comment]
Please re-open at https://github.com/neovim/node-client if necessary.

https://github.com/neovim/node-host repro is deprecated.
